## Импорт зависимостей

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

In [2]:
pd.set_option('display.max_columns', 50)

## Загрузка данных и разделение набора данных

In [3]:
from sklearn.model_selection import train_test_split

DATA_PATH = Path('../data')
TRAIN_PATH = DATA_PATH / 'train.csv'
TEST_PATH = DATA_PATH / 'test.csv'

TARGET = 'addicted_label'

TRAIN_DATA = pd.read_csv(TRAIN_PATH, index_col='id')
TEST_DATA = pd.read_csv(TEST_PATH, index_col='id')

X = TRAIN_DATA.drop(columns=TARGET)
y = TRAIN_DATA[TARGET]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=42)
X_test = TEST_DATA

In [4]:
X.shape

(691369, 12)

In [5]:
X.duplicated().sum()

np.int64(0)

## Понимание природы данных, их представления в датасете и количестве пропусков, дубликатов

Каждая строка данных представляет собой каждого отдельно взятого человека(всего их 691369). Нужно предсказать, зависим человек от телефона или нет

Строки(их значение в датасете и в реале):
- id - идентификатор каждого из участников - (нет пропусков)
- age - возраст - непрерывный числовой признак - (есть пропуски)
- daily_screen_time_hours - часы за экраном каждый день - непрерывный числовой признак - (есть пропуски)
- social_media_hours - часы в соцсетях - непрерывный числовой признак - (есть пропуски)
- gaming_hours - часы в играх - непрерывный числовой признак - (есть пропуски)
- work_study_hours - часы за работой/учебой - непрерывный числовой признак - (есть пропуски)
- sleep_hours - время сна - непрерывный числовой признак - (есть пропуски)
- notifications_per_day - количество уведомлений - счётный числовой признак - (есть пропуски)
- app_opens_per_day - количество приложений открытых за день - счетный числовой признак - (есть пропуски)
- weekend_screen_time - время за экраном в выходной - непрерывный числовой признак - (есть пропуски)
- gender - пол - номинальный категориальный признак - (есть пропуски) - мужчина, женщина, другой
- stress_level - уровень стресса - номинальный категориальный признак - (есть пропуски) - низкий, средний, высокий
- academic_work_impact - негативное влияние телефона на работу/учебу - номинальный категориальный признак  - есть пропуски - да, нет


### Неправильно
Идеи для преобразования данных:
- Признак - соотношение рабочих часов за экраном и количество часов в нерабочее время


### Правильно
Поскольку я буду делать упор на модели с градиентным бустингом, то в признаках-соотношениях других признаков смысла мало, тк такие модели сами находят линейные и нелинейные зависимости - нужно делать что-то другое:
- Признак - значение оставшегося времени, которое указано, как экранное, но не подходит под одну из выбранных категорий(соцсети, игры, работа)

In [6]:
X_train.head(10)

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact
id,,,,,,,,,,,,
285927,24.0,7.25,2.95,1.46,2.06,8.14,65.0,155.0,11.54,Male,Medium,Yes
285459,27.0,10.17,3.20,2.42,3.27,8.12,234.0,114.0,11.54,Female,Low,Yes
362545,27.0,2.90,0.78,0.22,1.57,6.60,142.0,39.0,5.67,NaN,NaN,NaN
268214,26.0,10.30,NaN,2.45,1.35,7.74,135.0,35.0,12.68,Other,Medium,Yes
71572,30.0,7.25,3.39,NaN,1.95,6.36,NaN,NaN,NaN,Male,High,Yes
15457,22.0,NaN,2.60,0.22,1.27,5.15,201.0,94.0,9.50,Female,Medium,Yes
220555,27.0,5.77,2.45,1.81,0.92,5.79,24.0,132.0,8.53,Male,Medium,Yes
680126,30.0,10.29,2.80,2.42,4.46,8.29,236.0,125.0,12.37,Male,Low,No
397807,25.0,3.41,0.83,0.70,1.65,5.89,215.0,78.0,5.69,Female,Medium,Yes
686312,33.0,5.40,0.62,1.76,2.26,8.96,22.0,54.0,10.82,Male,Medium,No

In [7]:
isnas = X_train['academic_work_impact'].isna().value_counts()
dups = X_train['academic_work_impact'].duplicated().sum()
counts_cats = X_train['academic_work_impact'].value_counts()
print(f"""-----
isNA:
-----
{isnas}
-----------
Duplicates:
-----------
{dups} / {X_train.shape[0]}
------------------------------
Value counts(for categorical):
------------------------------
{counts_cats}""")

-----
isNA:
-----
academic_work_impact
False    582292
True      39940
Name: count, dtype: int64
-----------
Duplicates:
-----------
622229 / 622232
------------------------------
Value counts(for categorical):
------------------------------
academic_work_impact
Yes    297553
No     284739
Name: count, dtype: int64

In [8]:
X_train.loc[(~(X_train['gender'].duplicated()))]

,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact
id,,,,,,,,,,,,
285927,24.0,7.25,2.95,1.46,2.06,8.14,65.0,155.0,11.54,Male,Medium,Yes
285459,27.0,10.17,3.20,2.42,3.27,8.12,234.0,114.0,11.54,Female,Low,Yes
362545,27.0,2.90,0.78,0.22,1.57,6.60,142.0,39.0,5.67,NaN,NaN,NaN
268214,26.0,10.30,NaN,2.45,1.35,7.74,135.0,35.0,12.68,Other,Medium,Yes

In [9]:
X_train.dtypes

age                        float64
daily_screen_time_hours    float64
social_media_hours         float64
gaming_hours               float64
work_study_hours           float64
sleep_hours                float64
notifications_per_day      float64
app_opens_per_day          float64
weekend_screen_time        float64
gender                         str
stress_level                   str
academic_work_impact           str
dtype: object

C типами данных всё ок - не вижу ничего странного

Заметки по ходу работы с ChatGPT по проекту:
- feature enginnering обычных моделей и моделей градиентного бустинга отличается, но не отменяется целиком. Какие-то признаки всё равно нужно создавать и отбирать: дельта рабочего и выходного дня, неразмеченное время и тд(вот тут поле для размышления не о простых долевых признаках, а о чем-то интереснее - искать бреши и возможности для комбинирования)
- часто пропуски можно оставить незаполненными(модели градиентного бустинга спокойно переваривают их), а кодирование категориальных признаков происходит автоматически(встроено под капотом таких моделей)
- для моделей градиентного бустинга пропуски - тоже информативное значение, поэтому их не стоит по дефолту импутировать
- пропуски в категориальных признаках лучше заменить с NaN на маркер неизвестного значения "unknown" и тп
- здесь полных дубликатов строк дфа нет, но в другом случае, если это не шум, двойное вхождение одной строки тоже имеет вес

Отбор признаков по такой схеме:

- здравого смысла
-       ↓
- baseline CV
-       ↓
- feature importance
-       ↓
- permutation importance / SHAP
-       ↓
- ablation experiments

**Нужно разузнать всё про пункты с 2 по последний**

**Важное уточнение - тюнинг гиперпараметров - поиск гиперпараметров для моделей-кандидатов, чтобы найти лучшую, а fine-tuning - тюнинг лучшей модели для получения лучшей производительности**

- Обе вышеуказанные процедуры можно проводить для CatBoost и XGBoost моделей так и нативными инструментами, так и привычным Grid/RandomizedSearch из sklearn
- *Early stopping* - то, за что мне нужно подшарить во время обучения моделей(это было в 4 главе HOMLP и мне нужно это наконец применить на практике и разобраться с этим вообще)
- О каждом прогоне модели нужно думать, как об эксперименте - нужно соответствующее оформление и использование интерфейсов библиотек для получения всевозможной инфы из тренировок, кросс-валидации и тюнинга моделей

Вот рекомендации от чатагпт по тому, как дальше развивать проект:

1. Сделать CatBoost baseline почти на сырых данных. Убрать очевидный мусор/leakage, оставить числовые NaN, нормально оформить categorical features, без scaling.
2. Сделать правильную validation-схему. Не трогать test до конца. Если классы — начать со StratifiedKFold.
3. Добавить eval_set + early stopping. Начать следить за best_iteration, train/validation metric и историей обучения.
4. Начать feature experiments. Для твоего датасета проверить хотя бы смысловые отношения вроде social_media_share, gaming_share, weekend_screen_delta, notifications_per_app_open. Каждый набор сравнивать через одинаковую CV.
5. Собирать таблицу экспериментов. Например model, features, params, cv_mean, cv_std, best_iteration, train_time. Это очень полезная привычка ещё до MLflow и прочего MLOps.
6. Только после стабильного baseline заниматься hyperparameter tuning. Сначала небольшой RandomizedSearchCV/CatBoost randomized_search, а позже имеет смысл перейти к Optuna.
7. После этого изучить feature importance → permutation importance → SHAP. Это уже следующий уровень интерпретации модели; CatBoost непосредственно предоставляет расчёт feature importance

## Подготовка признаков для Catboost

In [10]:
cat_cols = ['gender', 'stress_level', 'academic_work_impact']

for col in cat_cols:
    X_train[col] = X_train[col].fillna('Missing').astype(str)
    X_val[col] = X_val[col].fillna('Missing').astype(str)
    X_test[col] = X_test[col].fillna('Missing').astype(str)

In [11]:
X_train.dtypes

age                        float64
daily_screen_time_hours    float64
social_media_hours         float64
gaming_hours               float64
work_study_hours           float64
sleep_hours                float64
notifications_per_day      float64
app_opens_per_day          float64
weekend_screen_time        float64
gender                         str
stress_level                   str
academic_work_impact           str
dtype: object

## Создание базового catboost классификатора

In [ ]:
from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=10000
    ,           # Максимальное количество деревьев
    learning_rate=0.02,        # Насколько сильно каждое дерево меняет ансамбль
    depth=None,                # Глубина каждого из деревьев

    loss_function='Logloss',   # Что модель оптимизирует
    eval_metric='AUC',         # Метрика оценки

    random_seed=42,
    verbose=100,

    task_type='GPU'            # Использование видюхи вместо проца для обучения
)

In [13]:
cat_model.fit(
    X_train, 
    y_train,

    cat_features=cat_cols,

    eval_set=(X_val, y_val),

    early_stopping_rounds=200,
    use_best_model=True
)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9064970	best: 0.9064970 (0)	total: 3.37s	remaining: 9h 22m 16s
100:	test: 0.9293338	best: 0.9293338 (100)	total: 5.8s	remaining: 9m 28s
200:	test: 0.9344705	best: 0.9344705 (200)	total: 8.19s	remaining: 6m 39s
300:	test: 0.9379361	best: 0.9379361 (300)	total: 10.5s	remaining: 5m 38s
400:	test: 0.9403647	best: 0.9403647 (400)	total: 12.8s	remaining: 5m 6s
500:	test: 0.9424480	best: 0.9424480 (500)	total: 15.1s	remaining: 4m 45s
600:	test: 0.9441887	best: 0.9441887 (600)	total: 17.3s	remaining: 4m 31s
700:	test: 0.9456831	best: 0.9456831 (700)	total: 19.6s	remaining: 4m 20s
800:	test: 0.9471491	best: 0.9471491 (800)	total: 21.8s	remaining: 4m 10s
900:	test: 0.9482655	best: 0.9482655 (900)	total: 24.2s	remaining: 4m 4s
1000:	test: 0.9493386	best: 0.9493386 (1000)	total: 26.5s	remaining: 3m 58s
1100:	test: 0.9502855	best: 0.9502855 (1100)	total: 28.9s	remaining: 3m 53s
1200:	test: 0.9511092	best: 0.9511092 (1200)	total: 31.2s	remaining: 3m 48s
1300:	test: 0.9517993	best: 0.9517993 (1300)	total: 33.5s	remaining: 3m 44s
1400:	test: 0.9524298	best: 0.9524298 (1400)	total: 35.9s	remaining: 3m 40s
1500:	test: 0.9530253	best: 0.9530253 (1500)	total: 38.3s	remaining: 3m 36s
1600:	test: 0.9535866	best: 0.9535866 (1600)	total: 40.7s	remaining: 3m 33s
1700:	test: 0.9540532	best: 0.9540532 (1700)	total: 43s	remaining: 3m 29s
1800:	test: 0.9544982	best: 0.9544982 (1800)	total: 45.4s	remaining: 3m 26s
1900:	test: 0.9549181	best: 0.9549181 (1900)	total: 47.8s	remaining: 3m 23s
2000:	test: 0.9552844	best: 0.9552844 (2000)	total: 50.2s	remaining: 3m 20s
2100:	test: 0.9556059	best: 0.9556059 (2100)	total: 52.5s	remaining: 3m 17s
2200:	test: 0.9558759	best: 0.9558759 (2200)	total: 54.7s	remaining: 3m 13s
2300:	test: 0.9561821	best: 0.9561821 (2300)	total: 57.2s	remaining: 3m 11s
2400:	test: 0.9564305	best: 0.9564305 (2400)	total: 59.6s	remaining: 3m 8s
2500:	test: 0.9566646	best: 0.9566646 (2500)	total: 1m 2s	remaining: 3m 5s
2600:	test: 0.9569028	best: 0.9569028 (2600)	total: 1m 4s	remaining: 3m 3s
2700:	test: 0.9571095	best: 0.9571095 (2700)	total: 1m 6s	remaining: 3m
2800:	test: 0.9573079	best: 0.9573079 (2800)	total: 1m 9s	remaining: 2m 58s
2900:	test: 0.9575089	best: 0.9575089 (2900)	total: 1m 11s	remaining: 2m 55s
3000:	test: 0.9576963	best: 0.9576963 (3000)	total: 1m 14s	remaining: 2m 53s
3100:	test: 0.9578547	best: 0.9578547 (3100)	total: 1m 17s	remaining: 2m 52s
3200:	test: 0.9579920	best: 0.9579920 (3200)	total: 1m 20s	remaining: 2m 51s
3300:	test: 0.9581252	best: 0.9581252 (3300)	total: 1m 23s	remaining: 2m 49s
3400:	test: 0.9582619	best: 0.9582619 (3400)	total: 1m 25s	remaining: 2m 46s
3500:	test: 0.9583791	best: 0.9583791 (3500)	total: 1m 28s	remaining: 2m 44s
3600:	test: 0.9585121	best: 0.9585121 (3600)	total: 1m 31s	remaining: 2m 42s
3700:	test: 0.9586188	best: 0.9586188 (3700)	total: 1m 33s	remaining: 2m 39s
3800:	test: 0.9587269	best: 0.9587269 (3800)	total: 1m 36s	remaining: 2m 36s
3900:	test: 0.9588292	best: 0.9588292 (3899)	total: 1m 38s	remaining: 2m 34s
4000:	test: 0.9589264	best: 0.9589264 (4000)	total: 1m 41s	remaining: 2m 32s
4100:	test: 0.9590083	best: 0.9590083 (4100)	total: 1m 45s	remaining: 2m 31s
4200:	test: 0.9590798	best: 0.9590798 (4200)	total: 1m 48s	remaining: 2m 29s
4300:	test: 0.9591656	best: 0.9591656 (4298)	total: 1m 50s	remaining: 2m 26s
4400:	test: 0.9592329	best: 0.9592329 (4400)	total: 1m 52s	remaining: 2m 23s
4500:	test: 0.9592967	best: 0.9592967 (4500)	total: 1m 55s	remaining: 2m 20s
4600:	test: 0.9593673	best: 0.9593673 (4600)	total: 1m 57s	remaining: 2m 18s
4700:	test: 0.9594373	best: 0.9594373 (4700)	total: 2m	remaining: 2m 15s
4800:	test: 0.9594932	best: 0.9594932 (4800)	total: 2m 2s	remaining: 2m 12s
4900:	test: 0.9595492	best: 0.9595492 (4900)	total: 2m 5s	remaining: 2m 10s
5000:	test: 0.9596120	best: 0.9596120 (5000)	total: 2m 7s	remaining: 2m 7s
5100:	test: 0.9596756	best: 0.9596766 (5098)	total: 2m 10s	remaining: 2m 4s
5200:	test: 0.9597297	best: 0.9597297 (5200)	total: 2m 12s	remaining: 2m 2s
5300:	test: 0.9597852	best: 0.9597854 (5296)	total: 2m 14s	remaining: 1m 59s
5400:	test: 0.9598371	best: 0.9598371 (5400)	total: 2m 17s	remaining: 1m 56s
5500:	test: 0.9598843	best: 0.9598843 (5500)	total: 2m 19s	remaining: 1m 54s
5600:	test: 0.9599270	best: 0.9599270 (5600)	total: 2m 22s	remaining: 1m 51s
5700:	test: 0.9599661	best: 0.9599661 (5700)	total: 2m 25s	remaining: 1m 49s
5800:	test: 0.9600012	best: 0.9600012 (5800)	total: 2m 27s	remaining: 1m 46s
5900:	test: 0.9600330	best: 0.9600330 (5900)	total: 2m 30s	remaining: 1m 44s
6000:	test: 0.9600724	best: 0.9600724 (6000)	total: 2m 32s	remaining: 1m 41s
6100:	test: 0.9601133	best: 0.9601138 (6099)	total: 2m 35s	remaining: 1m 39s
6200:	test: 0.9601517	best: 0.9601518 (6199)	total: 2m 37s	remaining: 1m 36s
6300:	test: 0.9601825	best: 0.9601829 (6296)	total: 2m 40s	remaining: 1m 34s
6400:	test: 0.9602171	best: 0.9602171 (6400)	total: 2m 42s	remaining: 1m 31s
6500:	test: 0.9602450	best: 0.9602450 (6500)	total: 2m 45s	remaining: 1m 28s
6600:	test: 0.9602801	best: 0.9602807 (6599)	total: 2m 47s	remaining: 1m 26s
6700:	test: 0.9603012	best: 0.9603012 (6696)	total: 2m 49s	remaining: 1m 23s
6800:	test: 0.9603284	best: 0.9603284 (6800)	total: 2m 52s	remaining: 1m 20s
6900:	test: 0.9603542	best: 0.9603542 (6900)	total: 2m 54s	remaining: 1m 18s
7000:	test: 0.9603799	best: 0.9603803 (6999)	total: 2m 56s	remaining: 1m 15s
7100:	test: 0.9604053	best: 0.9604053 (7100)	total: 2m 59s	remaining: 1m 13s
7200:	test: 0.9604279	best: 0.9604281 (7199)	total: 3m 1s	remaining: 1m 10s
7300:	test: 0.9604521	best: 0.9604521 (7300)	total: 3m 4s	remaining: 1m 8s
7400:	test: 0.9604754	best: 0.9604754 (7400)	total: 3m 6s	remaining: 1m 5s
7500:	test: 0.9604940	best: 0.9604942 (7496)	total: 3m 9s	remaining: 1m 3s
7600:	test: 0.9605164	best: 0.9605164 (7600)	total: 3m 11s	remaining: 1m
7700:	test: 0.9605374	best: 0.9605374 (7700)	total: 3m 14s	remaining: 58.1s
7800:	test: 0.9605572	best: 0.9605572 (7797)	total: 3m 17s	remaining: 55.6s
7900:	test: 0.9605799	best: 0.9605799 (7900)	total: 3m 19s	remaining: 53s
8000:	test: 0.9605976	best: 0.9605990 (7999)	total: 3m 21s	remaining: 50.4s
8100:	test: 0.9606118	best: 0.9606122 (8091)	total: 3m 24s	remaining: 47.9s
8200:	test: 0.9606292	best: 0.9606296 (8195)	total: 3m 26s	remaining: 45.3s
8300:	test: 0.9606429	best: 0.9606433 (8297)	total: 3m 29s	remaining: 42.8s
8400:	test: 0.9606614	best: 0.9606615 (8399)	total: 3m 31s	remaining: 40.2s
8500:	test: 0.9606748	best: 0.9606753 (8497)	total: 3m 33s	remaining: 37.7s
8600:	test: 0.9606876	best: 0.9606876 (8600)	total: 3m 36s	remaining: 35.1s
8700:	test: 0.9606993	best: 0.9606997 (8698)	total: 3m 38s	remaining: 32.6s
8800:	test: 0.9607109	best: 0.9607114 (8789)	total: 3m 40s	remaining: 30.1s
8900:	test: 0.9607207	best: 0.9607207 (8900)	total: 3m 43s	remaining: 27.5s
9000:	test: 0.9607282	best: 0.9607285 (8999)	total: 3m 45s	remaining: 25.1s
9100:	test: 0.9607407	best: 0.9607407 (9096)	total: 3m 48s	remaining: 22.6s
9200:	test: 0.9607531	best: 0.9607531 (9200)	total: 3m 50s	remaining: 20.1s
9300:	test: 0.9607665	best: 0.9607665 (9299)	total: 3m 56s	remaining: 17.7s
9400:	test: 0.9607797	best: 0.9607801 (9399)	total: 3m 58s	remaining: 15.2s
9500:	test: 0.9607943	best: 0.9607943 (9500)	total: 4m 1s	remaining: 12.7s
9600:	test: 0.9608089	best: 0.9608089 (9600)	total: 4m 3s	remaining: 10.1s
9700:	test: 0.9608226	best: 0.9608226 (9699)	total: 4m 5s	remaining: 7.58s
9800:	test: 0.9608386	best: 0.9608386 (9800)	total: 4m 8s	remaining: 5.04s
9900:	test: 0.9608469	best: 0.9608470 (9891)	total: 4m 10s	remaining: 2.51s
9999:	test: 0.9608535	best: 0.9608540 (9994)	total: 4m 13s	remaining: 0us
bestTest = 0.9608539939
bestIteration = 9994
Shrink model to first 9995 iterations.

CatBoostClassifier(eval_metric='AUC', iterations=10000, learning_rate=0.02, loss_function='Logloss', random_seed=42, task_type='GPU', verbose=100)

In [14]:
print(f""" MODEL: baseline CatBoostClassifier

BEST ITERATION:

{cat_model.get_best_iteration()}

BEST SCORE:

{cat_model.get_best_score()}""")

 MODEL: baseline CatBoostClassifier

BEST ITERATION:

9994

BEST SCORE:

{'learn': {'Logloss': 0.21984075573901696}, 'validation': {'Logloss': 0.2297393049759897, 'AUC': 0.9608539938926697}}

## Функция оценивания модели

In [15]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score, 
    f1_score,
    roc_auc_score,
    log_loss,
    confusion_matrix,
)

def evaluate_classifier(model, X, y, threshold=0.53):
    proba = model.predict_proba(X)[:,1]
    pred = (proba >= threshold).astype(int)

    metrics = pd.Series({
        'roc_auc': roc_auc_score(y,proba),
        'log_loss': log_loss(y,proba),
        'accuracy': accuracy_score(y,pred),
        'precision': precision_score(y,pred, zero_division=0),
        'recall': recall_score(y,pred, zero_division=0),
        'f1': f1_score(y, pred, zero_division=0)
    })

    return metrics, confusion_matrix(y, pred)

In [16]:
cat_metrics, cat_cm = evaluate_classifier(
    cat_model,
    X_val,
    y_val
)

print(cat_metrics)
print(cat_cm)

roc_auc      0.960854
log_loss     0.229740
accuracy     0.898260
precision    0.928124
recall       0.927820
f1           0.927972
dtype: float64
[[16792  3509]
 [ 3525 45311]]

## То же самое на XGBoost

In [17]:
# попросить пояснение от иишки по этой ячейке

for col in cat_cols:
    categories = X_train[col].dropna().unique()

    dtype = pd.CategoricalDtype(
        categories=categories
    )

    X_train[col] = X_train[col].astype(dtype)
    X_val[col] = X_val[col].astype(dtype)
    X_test[col] = X_test[col].astype(dtype)

In [18]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=10000,
    learning_rate=0.02,

    subsample=0.8,
    colsample_bytree=0.8,

    eval_metric='auc',

    enable_categorical=True,

    early_stopping_rounds=200,

    random_state=42,
    n_jobs=-1
)

In [19]:
xgb_model.fit(
    X_train,
    y_train,
    eval_set = [(X_val, y_val)],
    verbose=100,
)

[0]	validation_0-auc:0.88780
[100]	validation_0-auc:0.93525
[200]	validation_0-auc:0.93879
[300]	validation_0-auc:0.94249
[400]	validation_0-auc:0.94685
[500]	validation_0-auc:0.95003
[600]	validation_0-auc:0.95242
[700]	validation_0-auc:0.95430
[800]	validation_0-auc:0.95582
[900]	validation_0-auc:0.95711
[1000]	validation_0-auc:0.95803
[1100]	validation_0-auc:0.95896
[1200]	validation_0-auc:0.95974
[1300]	validation_0-auc:0.96031
[1400]	validation_0-auc:0.96081
[1500]	validation_0-auc:0.96122
[1600]	validation_0-auc:0.96158
[1700]	validation_0-auc:0.96188
[1800]	validation_0-auc:0.96219
[1900]	validation_0-auc:0.96248
[2000]	validation_0-auc:0.96270
[2100]	validation_0-auc:0.96290
[2200]	validation_0-auc:0.96308
[2300]	validation_0-auc:0.96323
[2400]	validation_0-auc:0.96337
[2500]	validation_0-auc:0.96350
[2600]	validation_0-auc:0.96362
[2700]	validation_0-auc:0.96373
[2800]	validation_0-auc:0.96383
[2900]	validation_0-auc:0.96393
[3000]	validation_0-auc:0.96403
[3100]	validation_0-auc:0.96410
[3200]	validation_0-auc:0.96419
[3300]	validation_0-auc:0.96425
[3400]	validation_0-auc:0.96432
[3500]	validation_0-auc:0.96437
[3600]	validation_0-auc:0.96442
[3700]	validation_0-auc:0.96447
[3800]	validation_0-auc:0.96451
[3900]	validation_0-auc:0.96455
[4000]	validation_0-auc:0.96459
[4100]	validation_0-auc:0.96463
[4200]	validation_0-auc:0.96466
[4300]	validation_0-auc:0.96470
[4400]	validation_0-auc:0.96473
[4500]	validation_0-auc:0.96476
[4600]	validation_0-auc:0.96479
[4700]	validation_0-auc:0.96481
[4800]	validation_0-auc:0.96483
[4900]	validation_0-auc:0.96485
[5000]	validation_0-auc:0.96486
[5100]	validation_0-auc:0.96487
[5200]	validation_0-auc:0.96490
[5300]	validation_0-auc:0.96492
[5400]	validation_0-auc:0.96493
[5500]	validation_0-auc:0.96493
[5600]	validation_0-auc:0.96495
[5700]	validation_0-auc:0.96495
[5800]	validation_0-auc:0.96497
[5900]	validation_0-auc:0.96498
[6000]	validation_0-auc:0.96499
[6100]	validation_0-auc:0.96500
[6200]	validation_0-auc:0.96501
[6300]	validation_0-auc:0.96501
[6400]	validation_0-auc:0.96502
[6500]	validation_0-auc:0.96502
[6600]	validation_0-auc:0.96503
[6700]	validation_0-auc:0.96503
[6800]	validation_0-auc:0.96503
[6900]	validation_0-auc:0.96503
[7000]	validation_0-auc:0.96503
[7100]	validation_0-auc:0.96504
[7200]	validation_0-auc:0.96504
[7300]	validation_0-auc:0.96505
[7400]	validation_0-auc:0.96505
[7498]	validation_0-auc:0.96504

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=200,
              enable_categorical=True, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.02, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None,
              n_estimators=10000, n_jobs=-1, num_parallel_tree=None, ...)

In [20]:
print(f"""MODEL: XGBoostClassifier

BEST ITERATION

{xgb_model.best_iteration}

BEST SCORE

{xgb_model.best_score}

EVALUATION RESULTS

{xgb_model.evals_result()}
""")

MODEL: XGBoostClassifier

BEST ITERATION

7298

BEST SCORE

0.9650532415922414

EVALUATION RESULTS


In [21]:
xgb_metrics, xgb_cm = evaluate_classifier(
    xgb_model,
    X_val,
    y_val
)

print(xgb_metrics, )
xgb_cm

roc_auc      0.965053
log_loss     0.217066
accuracy     0.903293
precision    0.932024
recall       0.930994
f1           0.931509
dtype: float64

array([[16985,  3316],
       [ 3370, 45466]])

In [22]:
comparison = pd.DataFrame({
    'CatBoost': cat_metrics,
    'XGBoost': xgb_metrics
}).T

comparison

           roc_auc  log_loss  accuracy  precision    recall        f1
CatBoost  0.960854  0.229740  0.898260   0.928124  0.927820  0.927972
XGBoost   0.965053  0.217066  0.903293   0.932024  0.930994  0.931509